language: elixir
elixir:
    - 1.4
    - 1.5
opt_release:
    - 19.0

services:
  - docker

before_install:
  - docker build -t local/sozu ./sozu/
  - docker run -d -p 127.0.0.1:8080:8080 -v $(pwd)/data:/data local/sozu
  - sudo chown -R $USER:$USER ./data

script:
  - mix credo --strict
  - mix test
